config/routes.rb
Rails.application.routes.draw do
  root 'commuters#new'
  resources :commuters

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commuter.rb
class Commuter < ApplicationRecord
  has_one :home
  has_many :destinations
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :commuter

end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :commuter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/commuters_controller.rb
class CommutersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_commuter, only: [:show, :edit, :update, :destroy]

  # GET /commuters
  # GET /commuters.json
  def index
    @homes = Home.all
    @destinations = Destination.all
  end

  # GET /commuters/1
  # GET /commuters/1.json
  def show
  end

  # GET /commuters/new
  def new
    @commuter = Commuter.new
  end

  # GET /commuters/1/edit
  def edit
  end

  # POST /commuters
  # POST /commuters.json
  def create
    @commuter = Commuter.create
    @commuter.create_home(
      address: commuter_params[:home][:address],
      lat: commuter_params[:home][:coordinates][:lat],
      lng: commuter_params[:home][:coordinates][:lng]
    )

    commuter_params[:destinations].map do |destination|
      @commuter.destinations.create(
        address: destination[:address],
        lat: destination[:coordinates][:lat],
        lng: destination[:coordinates][:lng],
        place_type: destination[:type],
        mode: destination[:mode]
      )
    end

    respond_to do |format|
      if @commuter.save
        format.html { redirect_to @commuter, notice: 'Commuter was successfully created.' }
        format.json { render :show, status: :created, location: @commuter }
      else
        format.html { render :new }
        format.json { render json: @commuter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commuters/1
  # PATCH/PUT /commuters/1.json
  def update
    respond_to do |format|
      if @commuter.update(commuter_params)
        format.html { redirect_to @commuter, notice: 'Commuter was successfully updated.' }
        format.json { render :show, status: :ok, location: @commuter }
      else
        format.html { render :edit }
        format.json { render json: @commuter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commuters/1
  # DELETE /commuters/1.json
  def destroy
    @commuter.destroy
    respond_to do |format|
      format.html { redirect_to commuters_url, notice: 'Commuter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commuter
      @commuter = Commuter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commuter_params
      params.
        fetch(:commuter, {}).
        permit(home:
          [:address, :coordinates => [:lat, :lng]],
          :destinations => [:address, :type, :mode, :coordinates => [ :lat, :lng ]]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commuters_helper.rb
module CommutersHelper
end

app/views/commuters/_form.html.erb
<%= form_with(model: commuter, local: true) do |form| %>
  <% if commuter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(commuter.errors.count, "error") %> prohibited this commuter from being saved:</h2>

      <ul>
      <% commuter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= react_component("NewCommute") %>

  <div class="actions">
    <% form.submit "Submit" %>
  </div>
<% end %>

app/views/commuters/edit.html.erb
<h1>Editing Commuter</h1>

<%= render 'form', commuter: @commuter %>

<%= link_to 'Show', @commuter %> |
<%= link_to 'Back', commuters_path %>

app/views/commuters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Commuters</h1>

<%= react_component("MapContainer", { homes: @homes, destinations: @destinations }) %>

<br>

<%= link_to 'New Commuter', new_commuter_path %>

app/views/commuters/new.html.erb
<%= render 'form', commuter: @commuter %>

<%= link_to 'Back', commuters_path %>

app/views/commuters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_commuter_path(@commuter) %> |
<%= link_to 'Back', commuters_path %>

app/views/layouts/_header.html.erb
<nav>
  <%= image_tag "alta-logo.png", id: "logo", alt:"logo"%>
  <ul>
    <li>
      <%= link_to "All Commutes", commuters_path %>
    </li>
    <li>
      <%= link_to "New Commuter", new_commuter_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommuteStudy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main class="content">
      <%= yield %>
    </main>
  </body>
</html>